### ISSUE TITLE
System.Net.Mail.SmtpException: Server does not support secure connections.

### ISSUE THREAD

**Issue by SahibArora** [SahibArora/Home-Sweet-Home#1]
Error ----

System.Net.Mail.SmtpException: Server does not support secure connections.
   at System.Net.Mail.SmtpConnection.GetConnection(String host, Int32 port)
   at System.Net.Mail.SmtpTransport.GetConnection(String host, Int32 port)
   at System.Net.Mail.SmtpClient.GetConnection()
   at System.Net.Mail.SmtpClient.Send(MailMessage message)
   at Home_Sweet_Home.User.sendEmailVerificationCode(String email) in C:\Users\saror\Desktop\Home-Sweet-Home\Home-Sweet-Home\User.cs:line 200

**Was working fine before, all of the sudden there was an error!**

**Comment by SahibArora** [comment]
** Without any change in code its working **
Will be taken as a library [internal] caused problem not code defect.
